apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
spec:
  replicas: 1
  selector:
      matchLabels:
       app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
        - name: demo-java
          imagePullPolicy: Never
          image: demo-java:0.0.1
          resources:
            limits:
              cpu: 50m
              memory: 100Mi
            requests:
              cpu: 25m
              memory: 10Mi
          ports:
            - containerPort: 3000
          
---
apiVersion: v1
kind: Service
metadata:
  name: java-app
  namespace: default
spec:
  selector:
    app: helloworld
  type: NodePort
  ports:
    - targetPort:  3000
      port: 8080    